### ISSUE TITLE
Create a modal for the Products page

### ISSUE THREAD

**Issue by meejain** [aemsites/octoral#40] opened 2024-08-04 21:13 UTC
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/e1040240-a6b7-48fb-9d3e-23b01b0d0345">

**Comment by dave-fink** [comment] 2024-09-13 14:50
This is a duplicate of https://github.com/aemsites/octoral/issues/3

**Closed as completed by dave-fink** 2024-09-13 14:50 UTC
